### ISSUE TITLE
Error using sample

### ISSUE THREAD

**Issue by simar88** [STRML/node-xlsx-writestream#10]
Hi everyone!
I've got this error using the sample on documentation.

`
C:\Users\elaparo4d\Documents\Laparo_Development\Server\node_modules\xlsx-writest
ream\lib\index.js:287
    this.sheetStream = new PassThrough();
                       ^
TypeError: undefined is not a function
    at XlsxWriter.module.exports.XlsxWriter._resetSheet (C:\Users\elaparo4d\Docu
ments\Laparo_Development\Server\node_modules\xlsx-writestream\lib\index.js:287:2
4)
    at new XlsxWriter (C:\Users\elaparo4d\Documents\Laparo_Development\Server\no
de_modules\xlsx-writestream\lib\index.js:37:10)
    at Function.module.exports.XlsxWriter.write (C:\Users\elaparo4d\Documents\La
paro_Development\Server\node_modules\xlsx-writestream\lib\index.js:12:14)
    at Object.<anonymous> (C:\Users\elaparo4d\Documents\Laparo_Development\Serve
r\VideoLaparoscopy.js:2023:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by kaore** [comment]
worked fine for me in a linux environment.
